apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/tasbirul/k8s-voting-app.git'
    targetRevision: HEAD
    path: k8s-specifications
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: voting-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true