apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
      containers:
      - image: tasbirul/voting-app-result:88f0d36d20ebe0144a03d41b028708de2b584404
        name: result
        securityContext:
          readOnlyRootFilesystem: true
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        ports:
        - containerPort: 80
          name: result
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
      - name: tmp-volume
        emptyDir: {}