apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: tasbirul/examplevotingapp_result:a471c6f422a06048e26633fb36bbc578adebca58
        name: result
        ports:
        - containerPort: 80
          name: result
