apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: tasbirul/examplevotingapp_vote:ca8e4867420f5746f526a84a300976fb28990c1c
        name: vote
        ports:
        - containerPort: 80
          name: vote
