apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: tasbirul/examplevotingapp_worker:a9d108a7a15370be48671f5f010f8bda973cab76
        name: worker
